### ISSUE TITLE
babel-plugin-transform-es2015-block-scoping dep missing

### ISSUE THREAD

**Issue by jung-kim** [ariporad/babel-preset-features#3]
https://travis-ci.org/FredrikNoren/ungit/jobs/103527663
https://www.npmjs.com/package/babel-plugin-transform-es2015-block-scoping

it seems that `babel-plugin-transform-es2015-block-scoping` is missing from the dep list.

**Comment by ariporad** [comment]
Thanks for the bug report!

This has now been fixed in v2.0.5
