### ISSUE TITLE
plugins deps need to be updated

### ISSUE THREAD

**Issue by hax** [ariporad/babel-preset-features#4]
I just released `babel-features` 2.0.0 which is totally rewritten. 

Now it covers all es2015, stage 3 and stage 2 features. Some are even missed in `babel-preset-es2015` and `babel-preset-stage-X` --- such as `babel-plugin-syntax-function-sent`, `babel-plugin-transform-es2015-generator-return` ...

**Comment by ariporad** [comment]
Fixed in #5.
